export enum GameModeEvents {
    ValidateDifference = 'validate',
    DifferenceValidated = 'validated',
    EndGame = 'endGame',
    GameFinished = 'GameFinished',
    Abandoned = 'abandoned',
    CheckGame = 'checkGame',
    GameFound = 'gameFound',
    GameDeleted = 'gameDeleted',
    CanJoinGame = 'canJoinGame',
    CannotJoinGame = 'cannotJoinGame',
    NewBestTimeScore = 'newBestTimeScore',
    GameCanceled = 'gameCanceled',
    Timer = 'timer',
    ChangeTime = 'changeTime',
    NextGame = 'nextGame',
}
